name: Java CI/CD with Maven

on:
  push:
    branches: [feature-minhdan]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Run Unit Tests with Maven
        run: |
          cd backend
          mvn clean test
        env:
          DATASOURCE_URL: jdbc:mysql://localhost:3306/pms
          DATASOURCE_USERNAME: root
          DATASOURCE_PASSWORD: 12345

      - name: Build with Maven
        run: |
          cd backend
          mvn package
        env:
          DATASOURCE_URL: jdbc:mysql://localhost:3306/pms
          DATASOURCE_USERNAME: root
          DATASOURCE_PASSWORD: 12345

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: servlet-war
          path: backend/target/*.war
          if-no-files-found: error
